version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run:
          name: Install test dependencies
          command: pip install pycodestyle pyflakes
      - run:
          name: Install ffmpeg
          command: |
            sudo apt update
            sudo apt install -y ffmpeg
      - run:
          name: pyflakes
          command: pyflakes yledl/*.py
      - run:
          name: Code style check
          # E266 too many leading ‘#’ for block comment
          # W504 line break after binary operator
          command: |
            pycodestyle --ignore=E266,W504 --max-line-length 100 --statistics --count yledl/*.py || true
      - run:
          name: Smoke test
          command: yle-dl --help

  test:
    parameters:
        pyversion:
            type: string
    docker:
      - image: cimg/python:<< parameters.pyversion >>
    steps:
      - run:
          name: Install ffmpeg
          command: |
            sudo apt update
            sudo apt install -y ffmpeg
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
      - run:
          command: pip install pytest
      - run:
          name: Test
          command: |
            mkdir test-results
            python setup.py pytest --addopts "tests --junit-xml=test-results/report.xml"
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - lint
      - test:
          requires:
            - lint
          matrix:
              parameters:
                  pyversion: ["3.6", "3.7", "3.8", "3.9", "3.10"]
